"""
This file simulates AI-generated code.

Generated by:
Copilot / GPT Assistant

Purpose:
Generate quick summaries of NASA information.
"""


def generate_summary(apod_data):
    title = apod_data.get("title", "Unknown")
    explanation = apod_data.get("explanation", "")

    return f"NASA APOD: {title}\n{explanation[:250]}..."
