name: jessy-nasa-dashboard CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python build dependencies (FIX for pkg_resources error)
        run: |
          python -m pip install --upgrade pip setuptools wheel

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Black Duck Polaris Scan
        uses: blackduck-inc/black-duck-security-scan@v2
        with:
          polaris_server_url: ${{ secrets.POLARIS_SERVER_URL }}
          polaris_access_token: ${{ secrets.POLARIS_ACCESS_TOKEN }}
          polaris_application_name: jessy-nasa-dashboard
          polaris_project_name: jessy-nasa-dashboard
          polaris_branch_name: main
          polaris_assessment_types: "SCA"

          # IMPORTANT: remove invalid input detect_accuracy_required

          detect_args: >
            --detect.cleanup=false
            --detect.tools=DETECTOR